######################################################################
# Automatically generated by qmake (3.0) s�b fev 8 19:49:52 2014
######################################################################

TEMPLATE = app
TARGET = chess
INCLUDEPATH += .
QT += widgets
# Input
HEADERS += checkmate.h \
           chess.h \
           chooseblack.h \
           choosewhite.h \
           mainwindow.h
FORMS += checkmate.ui chooseblack.ui choosewhite.ui mainwindow.ui
SOURCES += chess.cpp chooseblack.cpp choosewhite.cpp main.cpp mainwindow.cpp
RESOURCES += img.qrc
